name: Deploy mdBook site to Pages

on:
  push:
    branches: ["main"]

  workflow_dispatch:
    inputs:
      ref:
        required: false
        type: string
        default: main
        description: |
          The git ref to deploy (ex. 'main', 'branch', '<commit sha>')

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

env:
  MDBOOK_VERSION: 0.4.21
  MDBOOK_ALERTS_VERSION: 0.6.7
  MDBOOK_LINKCHECK_VERSION: 0.7.7
  PUBLISH_DOMAIN: component-model.bytecodealliance.org
  ARTIFACT_PATH: ./component-model/book/html

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          ref: ${{ inputs.ref || 'main' }}

      - name: build mdbook
        uses: ./.github/actions/mdbook
        with:
          publish-pages-artifact: true

  deploy:
    if: ${{ github.repository_owner == 'bytecodealliance' }}
    needs:
      - build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@d6db90164ac5ed86f2b6aed7e0febac5b3c0c03e # v4.0.5
