name: Deploy mdBook site to Pages

on:
  push:
    branches: ["main"]

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

env:
  MDBOOK_VERSION: 0.4.21
  MDBOOK_ALERTS_VERSION: 0.6.7
  MDBOOK_LINKCHECK_VERSION: 0.7.7
  PUBLISH_DOMAIN: component-model.bytecodealliance.org
  ARTIFACT_PATH: ./component-model/book/html

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: taiki-e/cache-cargo-install-action@v2
        with:
          tool: mdbook@${{ env.MDBOOK_VERSION }}

      - uses: taiki-e/cache-cargo-install-action@v2
        with:
          tool: mdbook-alerts@${{ env.MDBOOK_ALERTS_VERSION }}

      - uses: taiki-e/cache-cargo-install-action@v2
        with:
          tool: mdbook-linkcheck@${{ env.MDBOOK_LINKCHECK_VERSION }}

      - name: Build with mdBook
        run: mdbook build component-model

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Ensure build outputs are present
        shell: bash
        run: |
          if [[ ! -f "${{ env.ARTIFACT_PATH }}/index.html" ]]; then
            echo "[error] index.html @ [${{ env.ARTIFACT_PATH }}] is missing. Build or path misconfigured";
            exit 1;
          fi

      - name: Generate sitemap
        shell: bash
        run: |
          cd ${{ env.ARTIFACT_PATH }}
          python3 ../../../scripts/generate_sitemap.py --domain "component-model.bytecodealliance.org" --higher-priority "design" --output-path sitemap.xml
          cd ../../../

      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v3

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ${{ env.ARTIFACT_PATH }}

  deploy:
    if: ${{ github.repository_owner == 'bytecodealliance' }}
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
